services:
  spark-driver:
    image: apache/spark:4.0.1-python3
    container_name: spark-driver
    entrypoint: [ "bash", "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4050:4040"
    volumes:
      - ./dataset:/dataset

  spark-executor:
    image: apache/spark:4.0.1-python3
    container_name: spark-executor
    entrypoint: [ "bash", "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-driver:7077" ]
    depends_on:
      - spark-driver
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  submit-job:
    image: apache/spark:4.0.1-python3
    container_name: submit-job
    environment:
      - DRIVER_URL=spark://spark-driver:7077
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=parquet-data

    entrypoint: [ "bash", "/app/submit.sh" ]
    depends_on:
      - minio
      - spark-driver
      - spark-executor

    volumes:
      - ./jobs.zip:/app/jobs.zip
      - ./main.py:/app/main.py
      - ./submit.sh:/app/submit.sh

volumes:
  minio_data: