services:
  spark-master:
    image: apache/spark:4.0.1-python3
    container_name: spark-master
    entrypoint: [ "bash", "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4050:4040"

  spark-worker:
    image: apache/spark:4.0.1-python3
    scale: 2
    entrypoint: [ "bash", "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077" ]
    depends_on:
      - spark-master

  spark-history-server:
    image: apache/spark:4.0.1-python3
    container_name: spark-history-server
    entrypoint: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer" ]
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/opt/spark/spark-events
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/opt/spark/spark-events

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  submit-job:
    image: apache/spark:4.0.1-python3
    container_name: submit-job
    environment:
      - MASTER_URL=spark://spark-master:7077
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=parquet-data

    entrypoint: [ "bash", "/app/submit.sh" ]
    depends_on:
      - minio
      - spark-master
      - spark-worker

    volumes:
      - ./jobs.zip:/app/jobs.zip
      - ./jobs/main.py:/app/main.py
      - ./scripts/submit.sh:/app/submit.sh
      - ./spark-events:/opt/spark/spark-events

volumes:
  minio_data: