[project]
name = "spark-high-volume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "minio>=7.2.20",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "pyspark>=4.0.1",
]
